-- Movie Data
LOAD DATA LOCAL INFILE "~/data/movie.del" INTO TABLE Movie FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

-- Actor Data
LOAD DATA LOCAL INFILE "~/data/actor1.del" INTO TABLE Actor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "~/data/actor2.del" INTO TABLE Actor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "~/data/actor3.del" INTO TABLE Actor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

-- Director Data
LOAD DATA LOCAL INFILE "~/data/director.del" INTO TABLE Director FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

-- -- Movie Genre Data
-- LOAD DATA LOCAL INFILE "~/data/moviegenre.del" INTO TABLE MovieGenre FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

-- -- Movie Director Data
-- LOAD DATA LOCAL INFILE "~/data/moviedirector.del" INTO TABLE MovieDirector FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

-- -- Movie Actor Data
-- LOAD DATA LOCAL INFILE "~/data/movieactor1.del" INTO TABLE MovieActor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
-- LOAD DATA LOCAL INFILE "~/data/movieactor2.del" INTO TABLE MovieActor FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';